1790027607 /prj/ci/workarea/aluno3/ProjetosCarneiro/CI_Digital/Phase2/SD242_Verificaçao de Sistemas Digitais/Functional_coverage/ula_coverage_mod/top_tb.sv
1790027607 /prj/ci/workarea/aluno3/ProjetosCarneiro/CI_Digital/Phase2/SD242_Verificaçao de Sistemas Digitais/Functional_coverage/ula_coverage_mod/ula_coverage.sv
1790029087 /prj/ci/workarea/aluno3/ProjetosCarneiro/CI_Digital/Phase2/SD242_Verificaçao de Sistemas Digitais/Functional_coverage/ula_coverage_mod/ula_item.sv
1790027607 /prj/ci/workarea/aluno3/ProjetosCarneiro/CI_Digital/Phase2/SD242_Verificaçao de Sistemas Digitais/Functional_coverage/ula_coverage_mod/ula_env_config.sv
1790029087 /prj/ci/workarea/aluno3/ProjetosCarneiro/CI_Digital/Phase2/SD242_Verificaçao de Sistemas Digitais/Functional_coverage/ula_coverage_mod/ula_driver.sv
1790027607 /prj/ci/workarea/aluno3/ProjetosCarneiro/CI_Digital/Phase2/SD242_Verificaçao de Sistemas Digitais/Functional_coverage/ula_coverage_mod/ula_scoreboard.sv
1790027607 /prj/ci/workarea/aluno3/ProjetosCarneiro/CI_Digital/Phase2/SD242_Verificaçao de Sistemas Digitais/Functional_coverage/ula_coverage_mod/ula.sv
1790029087 /prj/ci/workarea/aluno3/ProjetosCarneiro/CI_Digital/Phase2/SD242_Verificaçao de Sistemas Digitais/Functional_coverage/ula_coverage_mod/ula_monitor.sv
1790027607 /prj/ci/workarea/aluno3/ProjetosCarneiro/CI_Digital/Phase2/SD242_Verificaçao de Sistemas Digitais/Functional_coverage/ula_coverage_mod/ula_test.sv
1790029087 /prj/ci/workarea/aluno3/ProjetosCarneiro/CI_Digital/Phase2/SD242_Verificaçao de Sistemas Digitais/Functional_coverage/ula_coverage_mod/ula_env.sv
1790027607 /prj/ci/workarea/aluno3/ProjetosCarneiro/CI_Digital/Phase2/SD242_Verificaçao de Sistemas Digitais/Functional_coverage/ula_coverage_mod/ula_agent_config.sv
1790029087 /prj/ci/workarea/aluno3/ProjetosCarneiro/CI_Digital/Phase2/SD242_Verificaçao de Sistemas Digitais/Functional_coverage/ula_coverage_mod/ula_sequence.sv
1790029087 /prj/ci/workarea/aluno3/ProjetosCarneiro/CI_Digital/Phase2/SD242_Verificaçao de Sistemas Digitais/Functional_coverage/ula_coverage_mod/ula_sequencer.sv
1790029087 /prj/ci/workarea/aluno3/ProjetosCarneiro/CI_Digital/Phase2/SD242_Verificaçao de Sistemas Digitais/Functional_coverage/ula_coverage_mod/ula_agent.sv
1790028078 /prj/ci/workarea/aluno3/ProjetosCarneiro/CI_Digital/Phase2/SD242_Verificaçao de Sistemas Digitais/Functional_coverage/ula_coverage_mod/ula_if.sv
