
// Generated by Cadence Genus(TM) Synthesis Solution 22.16-s078_1
// Generated on: Aug 18 2026 20:13:51 -03 (Aug 18 2026 23:13:51 UTC)

// Verification Directory fv/x3_curto 

module x3_curto(XPower, X, clk);
  input [7:0] X;
  input clk;
  output [7:0] XPower;
  wire [7:0] X;
  wire clk;
  wire [7:0] XPower;
  wire [7:0] XPower2;
  wire [7:0] X1;
  wire [7:0] X2;
  wire mul_19_27_n_0, mul_19_27_n_1, mul_19_27_n_2, mul_19_27_n_3,
       mul_19_27_n_4, mul_19_27_n_5, mul_19_27_n_6, mul_19_27_n_7;
  wire mul_19_27_n_8, mul_19_27_n_9, mul_19_27_n_10, mul_19_27_n_11,
       mul_19_27_n_12, mul_19_27_n_13, mul_19_27_n_14, mul_19_27_n_15;
  wire mul_19_27_n_16, mul_19_27_n_17, mul_19_27_n_18, mul_19_27_n_19,
       mul_19_27_n_20, mul_19_27_n_22, mul_19_27_n_23, mul_19_27_n_24;
  wire mul_19_27_n_25, mul_19_27_n_26, mul_19_27_n_27, mul_19_27_n_28,
       mul_19_27_n_29, mul_19_27_n_30, mul_19_27_n_31, mul_19_27_n_32;
  wire mul_19_27_n_33, mul_19_27_n_34, mul_19_27_n_35, mul_19_27_n_36,
       mul_19_27_n_37, mul_19_27_n_38, mul_19_27_n_39, mul_19_27_n_41;
  wire mul_19_27_n_42, mul_19_27_n_43, mul_19_27_n_44, mul_19_27_n_45,
       mul_19_27_n_46, mul_19_27_n_47, mul_19_27_n_48, mul_19_27_n_49;
  wire mul_19_27_n_50, mul_19_27_n_51, mul_19_27_n_52, mul_19_27_n_53,
       mul_19_27_n_55, mul_19_27_n_56, mul_19_27_n_57, mul_19_27_n_58;
  wire mul_19_27_n_59, mul_19_27_n_60, mul_19_27_n_61, mul_19_27_n_63,
       mul_19_27_n_64, mul_19_27_n_66, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51;
  DFFHQX1 \XPower2_reg[7] (.CK (clk), .D (n_35), .Q (XPower2[7]));
  XNOR2X1 g577__2398(.A (n_30), .B (n_33), .Y (n_35));
  DFFHQX1 \XPower2_reg[6] (.CK (clk), .D (n_34), .Q (XPower2[6]));
  ADDFX1 g579__5107(.A (n_16), .B (n_27), .CI (n_31), .CO (n_33), .S
       (n_34));
  DFFHQX1 \XPower2_reg[5] (.CK (clk), .D (n_32), .Q (XPower2[5]));
  ADDFX1 g581__6260(.A (n_0), .B (n_17), .CI (n_20), .CO (n_31), .S
       (n_32));
  DFFHQX1 \XPower2_reg[4] (.CK (clk), .D (n_29), .Q (XPower2[4]));
  XNOR2X1 g583__4319(.A (n_26), .B (n_25), .Y (n_30));
  XNOR2X1 g584__8428(.A (n_15), .B (n_28), .Y (n_29));
  XNOR2X1 g585__5526(.A (n_0), .B (n_21), .Y (n_28));
  XNOR2X1 g586__6783(.A (n_14), .B (n_24), .Y (n_27));
  OA22X1 g587__3680(.A0 (n_14), .A1 (n_23), .B0 (n_4), .B1 (n_12), .Y
       (n_26));
  DFFHQX1 \XPower2_reg[3] (.CK (clk), .D (n_22), .Q (XPower2[3]));
  XNOR2X1 g589__1617(.A (n_19), .B (n_18), .Y (n_25));
  ADDHX1 g590__2802(.A (n_4), .B (n_12), .CO (n_23), .S (n_24));
  DFFHQX1 \XPower2_reg[2] (.CK (clk), .D (n_13), .Q (XPower2[2]));
  AOI21X1 g592__1705(.A0 (n_6), .A1 (n_10), .B0 (n_15), .Y (n_22));
  XNOR2X1 g593__5122(.A (X1[2]), .B (n_5), .Y (n_21));
  XOR2XL g594__8246(.A (n_8), .B (n_9), .Y (n_20));
  XNOR2X1 g595__7098(.A (n_2), .B (n_3), .Y (n_19));
  XNOR2X1 g596__6131(.A (n_11), .B (n_7), .Y (n_18));
  NOR2X1 g597__1881(.A (n_1), .B (n_5), .Y (n_17));
  NOR2X1 g598__5115(.A (n_9), .B (n_8), .Y (n_16));
  AND2XL g599__7482(.A (X1[1]), .B (n_6), .Y (n_13));
  NOR2X1 g600__4733(.A (n_6), .B (n_10), .Y (n_15));
  NAND2XL g601__6161(.A (X1[3]), .B (n_7), .Y (n_14));
  DFFHQX1 \X2_reg[1] (.CK (clk), .D (X1[1]), .Q (X2[1]));
  DFFHQX1 \X2_reg[3] (.CK (clk), .D (X1[3]), .Q (X2[3]));
  DFFHQX1 \X2_reg[2] (.CK (clk), .D (X1[2]), .Q (X2[2]));
  DFFHQX1 \X2_reg[4] (.CK (clk), .D (X1[4]), .Q (X2[4]));
  DFFHQX1 \X2_reg[5] (.CK (clk), .D (X1[5]), .Q (X2[5]));
  DFFHQX1 \X2_reg[6] (.CK (clk), .D (X1[6]), .Q (X2[6]));
  DFFHQX1 \X2_reg[7] (.CK (clk), .D (X1[7]), .Q (X2[7]));
  NAND2XL g609__9315(.A (X1[5]), .B (X1[1]), .Y (n_11));
  DFFHQX1 \X2_reg[0] (.CK (clk), .D (X1[0]), .Q (X2[0]));
  NAND2XL g611__9945(.A (X1[1]), .B (X1[4]), .Y (n_12));
  NAND2X1 g612__2883(.A (X1[2]), .B (X1[4]), .Y (n_3));
  NAND2X1 g613__2346(.A (X1[0]), .B (X1[2]), .Y (n_10));
  NAND2XL g614__1666(.A (X1[6]), .B (X1[0]), .Y (n_2));
  NAND2X1 g615__7410(.A (X1[0]), .B (X1[4]), .Y (n_9));
  NAND2X1 g616__6417(.A (X1[1]), .B (X1[3]), .Y (n_8));
  NAND2X1 g617__5477(.A (X1[2]), .B (X1[3]), .Y (n_7));
  NAND2X1 g618__2398(.A (X1[0]), .B (X1[1]), .Y (n_6));
  NAND2X1 g619__5107(.A (X1[0]), .B (X1[3]), .Y (n_5));
  NAND2X1 g620__6260(.A (X1[5]), .B (X1[0]), .Y (n_4));
  INVX1 g622(.A (X1[2]), .Y (n_1));
  DFFQXL \XPower_reg[6] (.CK (clk), .D (n_46), .Q (XPower[6]));
  DFFQXL \XPower_reg[5] (.CK (clk), .D (n_47), .Q (XPower[5]));
  DFFQXL \XPower_reg[7] (.CK (clk), .D (n_45), .Q (XPower[7]));
  DFFQXL \XPower_reg[2] (.CK (clk), .D (n_50), .Q (XPower[2]));
  DFFQXL \XPower_reg[0] (.CK (clk), .D (X2[0]), .Q (XPower[0]));
  DFFHQX1 \X1_reg[5] (.CK (clk), .D (X[5]), .Q (X1[5]));
  DFFHQX1 \X1_reg[3] (.CK (clk), .D (X[3]), .Q (X1[3]));
  DFFHQX1 \X1_reg[2] (.CK (clk), .D (X[2]), .Q (X1[2]));
  DFFQXL \XPower_reg[3] (.CK (clk), .D (n_49), .Q (XPower[3]));
  DFFQXL \XPower_reg[1] (.CK (clk), .D (n_51), .Q (XPower[1]));
  DFFQXL \X1_reg[7] (.CK (clk), .D (X[7]), .Q (X1[7]));
  DFFQXL \XPower_reg[4] (.CK (clk), .D (n_48), .Q (XPower[4]));
  DFFQXL \X1_reg[6] (.CK (clk), .D (X[6]), .Q (X1[6]));
  DFFHQX1 \X1_reg[4] (.CK (clk), .D (X[4]), .Q (X1[4]));
  DFFHQX1 \X1_reg[0] (.CK (clk), .D (X[0]), .Q (X1[0]));
  DFFHQX1 \X1_reg[1] (.CK (clk), .D (X[1]), .Q (X1[1]));
  NOR2BX1 g2__4319(.AN (X1[1]), .B (n_1), .Y (n_0));
  XNOR2X1 mul_19_27_g480__8428(.A (mul_19_27_n_63), .B
       (mul_19_27_n_66), .Y (n_45));
  ADDFX1 mul_19_27_g481__5526(.A (mul_19_27_n_55), .B (mul_19_27_n_59),
       .CI (mul_19_27_n_64), .CO (mul_19_27_n_66), .S (n_46));
  ADDFX1 mul_19_27_g482__6783(.A (mul_19_27_n_47), .B (mul_19_27_n_56),
       .CI (mul_19_27_n_61), .CO (mul_19_27_n_64), .S (n_47));
  XNOR2X1 mul_19_27_g483__3680(.A (mul_19_27_n_58), .B
       (mul_19_27_n_60), .Y (mul_19_27_n_63));
  ADDFX1 mul_19_27_g484__1617(.A (mul_19_27_n_30), .B (mul_19_27_n_48),
       .CI (mul_19_27_n_53), .CO (mul_19_27_n_61), .S (n_48));
  XNOR2X1 mul_19_27_g485__2802(.A (mul_19_27_n_57), .B
       (mul_19_27_n_52), .Y (mul_19_27_n_60));
  ADDFX1 mul_19_27_g486__1705(.A (mul_19_27_n_45), .B (mul_19_27_n_44),
       .CI (mul_19_27_n_51), .CO (mul_19_27_n_58), .S (mul_19_27_n_59));
  XNOR2X1 mul_19_27_g487__5122(.A (mul_19_27_n_42), .B
       (mul_19_27_n_50), .Y (mul_19_27_n_57));
  ADDFX1 mul_19_27_g488__8246(.A (mul_19_27_n_29), .B (mul_19_27_n_33),
       .CI (mul_19_27_n_46), .CO (mul_19_27_n_55), .S (mul_19_27_n_56));
  ADDFX1 mul_19_27_g489__7098(.A (mul_19_27_n_3), .B (mul_19_27_n_28),
       .CI (mul_19_27_n_34), .CO (mul_19_27_n_53), .S (n_49));
  XNOR2X1 mul_19_27_g490__6131(.A (mul_19_27_n_41), .B
       (mul_19_27_n_49), .Y (mul_19_27_n_52));
  ADDFX1 mul_19_27_g491__1881(.A (mul_19_27_n_4), .B (mul_19_27_n_31),
       .CI (mul_19_27_n_35), .CO (mul_19_27_n_50), .S (mul_19_27_n_51));
  XNOR2X1 mul_19_27_g492__5115(.A (mul_19_27_n_37), .B
       (mul_19_27_n_43), .Y (mul_19_27_n_49));
  ADDFX1 mul_19_27_g493__7482(.A (mul_19_27_n_14), .B (mul_19_27_n_15),
       .CI (mul_19_27_n_36), .CO (mul_19_27_n_47), .S (mul_19_27_n_48));
  ADDFX1 mul_19_27_g494__4733(.A (mul_19_27_n_1), .B (mul_19_27_n_0),
       .CI (mul_19_27_n_17), .CO (mul_19_27_n_45), .S (mul_19_27_n_46));
  ADDFX1 mul_19_27_g495__6161(.A (mul_19_27_n_2), .B (mul_19_27_n_16),
       .CI (mul_19_27_n_18), .CO (mul_19_27_n_43), .S (mul_19_27_n_44));
  XNOR2X1 mul_19_27_g496__9315(.A (mul_19_27_n_32), .B
       (mul_19_27_n_39), .Y (mul_19_27_n_42));
  XNOR2X1 mul_19_27_g497__9945(.A (mul_19_27_n_7), .B (mul_19_27_n_38),
       .Y (mul_19_27_n_41));
  AOI21X1 mul_19_27_g498__2883(.A0 (mul_19_27_n_27), .A1
       (mul_19_27_n_26), .B0 (mul_19_27_n_28), .Y (n_50));
  XNOR2X1 mul_19_27_g499__2346(.A (mul_19_27_n_20), .B (mul_19_27_n_8),
       .Y (mul_19_27_n_39));
  XNOR2X1 mul_19_27_g500__1666(.A (mul_19_27_n_19), .B (mul_19_27_n_9),
       .Y (mul_19_27_n_38));
  XNOR2X1 mul_19_27_g501__7410(.A (mul_19_27_n_6), .B (mul_19_27_n_5),
       .Y (mul_19_27_n_37));
  XOR2XL mul_19_27_g502__6417(.A (mul_19_27_n_22), .B (mul_19_27_n_11),
       .Y (mul_19_27_n_36));
  XOR2XL mul_19_27_g503__5477(.A (mul_19_27_n_25), .B (mul_19_27_n_24),
       .Y (mul_19_27_n_35));
  XOR2XL mul_19_27_g504__2398(.A (mul_19_27_n_10), .B (mul_19_27_n_12),
       .Y (mul_19_27_n_34));
  XOR2XL mul_19_27_g505__5107(.A (mul_19_27_n_13), .B (mul_19_27_n_23),
       .Y (mul_19_27_n_33));
  NOR2XL mul_19_27_g506__6260(.A (mul_19_27_n_25), .B (mul_19_27_n_24),
       .Y (mul_19_27_n_32));
  NOR2X1 mul_19_27_g507__4319(.A (mul_19_27_n_13), .B (mul_19_27_n_23),
       .Y (mul_19_27_n_31));
  NOR2X1 mul_19_27_g508__8428(.A (mul_19_27_n_12), .B (mul_19_27_n_10),
       .Y (mul_19_27_n_30));
  NOR2X1 mul_19_27_g509__5526(.A (mul_19_27_n_11), .B (mul_19_27_n_22),
       .Y (mul_19_27_n_29));
  NOR2X1 mul_19_27_g510__6783(.A (mul_19_27_n_27), .B (mul_19_27_n_26),
       .Y (mul_19_27_n_28));
  AND2XL mul_19_27_g511__3680(.A (X2[1]), .B (X2[0]), .Y (n_51));
  NAND2XL mul_19_27_g512__1617(.A (X2[5]), .B (XPower2[2]), .Y
       (mul_19_27_n_20));
  NAND2XL mul_19_27_g513__2802(.A (X2[2]), .B (XPower2[5]), .Y
       (mul_19_27_n_19));
  NAND2X1 mul_19_27_g514__1705(.A (X2[2]), .B (X2[0]), .Y
       (mul_19_27_n_27));
  NAND2X1 mul_19_27_g515__5122(.A (XPower2[2]), .B (X2[0]), .Y
       (mul_19_27_n_26));
  NAND2X1 mul_19_27_g516__8246(.A (X2[1]), .B (XPower2[5]), .Y
       (mul_19_27_n_25));
  AND2XL mul_19_27_g517__7098(.A (X2[6]), .B (X2[0]), .Y
       (mul_19_27_n_18));
  NAND2X1 mul_19_27_g518__6131(.A (XPower2[6]), .B (X2[0]), .Y
       (mul_19_27_n_24));
  NAND2X1 mul_19_27_g519__1881(.A (XPower2[5]), .B (X2[0]), .Y
       (mul_19_27_n_23));
  AND2XL mul_19_27_g520__5115(.A (X2[5]), .B (X2[0]), .Y
       (mul_19_27_n_17));
  NAND2X1 mul_19_27_g521__7482(.A (X2[1]), .B (XPower2[3]), .Y
       (mul_19_27_n_22));
  AND2XL mul_19_27_g522__4733(.A (X2[3]), .B (XPower2[3]), .Y
       (mul_19_27_n_16));
  AND2XL mul_19_27_g523__6161(.A (X2[4]), .B (X2[0]), .Y
       (mul_19_27_n_15));
  AND2XL mul_19_27_g524__9315(.A (X2[2]), .B (XPower2[2]), .Y
       (mul_19_27_n_14));
  NAND2X1 mul_19_27_g525__9945(.A (X2[4]), .B (XPower2[3]), .Y
       (mul_19_27_n_9));
  NAND2X1 mul_19_27_g526__2883(.A (X2[7]), .B (X2[0]), .Y
       (mul_19_27_n_8));
  NAND2XL mul_19_27_g527__2346(.A (X2[3]), .B (XPower2[4]), .Y
       (mul_19_27_n_7));
  NAND2XL mul_19_27_g528__1666(.A (XPower2[6]), .B (X2[1]), .Y
       (mul_19_27_n_6));
  NAND2X1 mul_19_27_g529__7410(.A (XPower2[7]), .B (X2[0]), .Y
       (mul_19_27_n_5));
  NAND2X1 mul_19_27_g530__6417(.A (X2[1]), .B (XPower2[4]), .Y
       (mul_19_27_n_13));
  NAND2X1 mul_19_27_g531__5477(.A (XPower2[3]), .B (X2[0]), .Y
       (mul_19_27_n_12));
  NAND2X1 mul_19_27_g532__2398(.A (XPower2[4]), .B (X2[0]), .Y
       (mul_19_27_n_11));
  NAND2X1 mul_19_27_g533__5107(.A (X2[1]), .B (XPower2[2]), .Y
       (mul_19_27_n_10));
  AND2XL mul_19_27_g534__6260(.A (X2[2]), .B (XPower2[4]), .Y
       (mul_19_27_n_4));
  AND2XL mul_19_27_g535__4319(.A (X2[3]), .B (X2[0]), .Y
       (mul_19_27_n_3));
  AND2XL mul_19_27_g536__8428(.A (X2[4]), .B (XPower2[2]), .Y
       (mul_19_27_n_2));
  AND2XL mul_19_27_g537__5526(.A (X2[3]), .B (XPower2[2]), .Y
       (mul_19_27_n_1));
  AND2XL mul_19_27_g538__6783(.A (X2[2]), .B (XPower2[3]), .Y
       (mul_19_27_n_0));
endmodule

